#! /bin/sh

bspc monitor -d I II III IV

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52

# Monocle
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config single_monocle true

bspc config top_monocle_padding 24
bspc config right_monocle_padding 36
bspc config bottom_monocle_padding 24
bspc config left_monocle_padding 36

bspc rule -a kitty desktop='^1' follow=on
# seems to focus despite follow=off
bspc rule -a Zathura desktop='^1' state=tiled follow=off
# failed experiment: only apply rule to certain zathura windows based on path in window title. prob use 'external rules command' for this
# bspc rule -a "*:*:/home/tom/docs/job/applications/werkstudent/de_HPI_kursmanagement_moti.pdf" desktop='^1' state=tiled
bspc rule -a ghidra-Ghidra desktop='^3' state=floating follow=off
# bspc rule -a "*" desktop='^2' follow=on
