#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52

# Monocle
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config single_monocle true

bspc config top_monocle_padding 12
bspc config right_monocle_padding 12
bspc config bottom_monocle_padding 12
bspc config left_monocle_padding 12

bspc rule -a "*" desktop='^2' follow=on
bspc rule -a kitty desktop='^1' follow=on
bspc rule -a Zathura state=tiled
