[colors]
background = #463338
foreground = #1a0e04
primary    = #1a6e8a
secondary  = #2eaabc
alert      = #cc1010
disabled   = #8a6840
 
[bar/main]
width = 100%
height = 20pt
radius = 0

font-0 = "FiraCode Nerd Font Mono:size=11;3"
# Your CJK Fallback (The Vaporwave Specialist)
# We use the name exactly as it appeared: "VL Gothic"
font-1 = "VL Gothic:size=11;2"

# Optional: A dedicated Icon font if some icons are still missing
font-2 = "Symbols Nerd Font:size=12;3"

background = ${colors.background}
foreground = ${colors.foreground}

# 'Padding' OUTSIDE the bar (the floating effect)
# This creates a 5pt gap at the top and 5pt on the sides
# border-size = 5pt
# border-color = #00000000  ; The '00' at the start makes it transparent

# To center content vertically, ensure 'line-size' is 0 
# or use it specifically for underlines
line-size = 0

padding-left = 1
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.primary}

# These are the three sections: Left, Center, Right
modules-left = bspwm
modules-center = xwindow
modules-right = volume date

cursor-click = pointer
enable-ipc = true

# This ensures the bar doesn't hide your windows
# This tells Polybar NOT to reserve space automatically
override-redirect = true
# This tells the bar to stay at the very bottom of the window stack
wm-restack = bspwm

[module/bspwm]
type = internal/bspwm
label-focused = %name%
label-focused-background = ${colors.primary}
label-focused-foreground = ${colors.background}
label-focused-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = #565f89
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/volume]
type = custom/script
# tail = true tells Polybar to keep the script running and update on every new line
tail = true
exec = vol-hook
label-foreground = ${colors.primary}

[module/date]
type = internal/date
interval = 60
; date = %H:%M
date = %A,  %B  %e •  %H:%M
# date = %Y/%m/%d (%a) %H:%M
label = %date%
label-foreground = ${colors.secondary}
label-padding = 2
